### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [72]:
import numpy as np
import random

# 1. Вектор (через np.random.rand)
vector = np.random.rand(10)

# 2. Альтернативний варіант (через random.uniform)
vector2 = np.array([random.uniform(0, 1) for _ in range(10)])

# 3. Матриця 3x3 (задані значення)
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

# Вивід результатів
print("Вектор (np.random.rand):")
print(vector)

print("\nВектор (random.uniform):")
print(vector2)

print("\nМатриця 3x3:")
print(matrix)

# Розміри
print("\nРозміри:")
print("vector shape:", vector.shape)
print("vector2 shape:", vector2.shape)
print("matrix shape:", matrix.shape)

Вектор (np.random.rand):
[0.65303345 0.95452228 0.873951   0.06056304 0.71269916 0.64643997
 0.50160009 0.87348049 0.35970846 0.24782755]

Вектор (random.uniform):
[0.61397433 0.17301329 0.304424   0.01138656 0.06269926 0.66115346
 0.10288606 0.95133036 0.82221979 0.70519414]

Матриця 3x3:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Розміри:
vector shape: (10,)
vector2 shape: (10,)
matrix shape: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [76]:
# 1. Додати 10 і округлити
vector_plus_10 = np.round(vector + 10, 2)
print("Вектор +10:")
print(vector_plus_10)

# 2. Помножити матрицю на 2
matrix_times_2 = matrix * 2
print("\nМатриця *2:")
print(matrix_times_2)

# 3. Квадрат кожного елемента вектора
vector_squared = vector ** 2
print("\nВектор у квадраті:")
print(vector_squared)

Вектор +10:
[10.65 10.95 10.87 10.06 10.71 10.65 10.5  10.87 10.36 10.25]

Матриця *2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]

Вектор у квадраті:
[0.42645269 0.91111278 0.76379034 0.00366788 0.50794009 0.41788464
 0.25160265 0.76296817 0.12939018 0.0614185 ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [80]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [82]:
# 1. Множення матриць (отримуємо 2x2)
result_matrix = np.dot(B, A)
print("Result matrix (2x2):")
print(result_matrix)


# 2. Множення на вектор (2x1)
multiply = np.dot(result_matrix, C)
print("\nResult * C (2x1):")
print(multiply)


# 3. Множення на матрицю D (2x2)
multiply2 = np.dot(result_matrix, D)
print("\nResult * D (2x2):")
print(multiply2)


Result matrix (2x2):
[[0.7281 0.5202]
 [0.2034 0.2846]]

Result * C (2x1):
[[0.5202]
 [0.2846]]

Result * D (2x2):
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [98]:
# 1. Транспонування матриці
result_matrix_T = result_matrix.T
print("Транспонована матриця:")
print(result_matrix_T)


# 2. Транспонування вектора
vector_T = vector.T
print("\nВектор і його транспонування:")
print("vector:", vector)
print("vector_T:", vector_T)

print("\nРозміри:")
print("vector shape:", vector.shape)
print("vector_T shape:", vector_T.shape)


# 3. expand_dims (робимо стовпець)
column_vector = np.expand_dims(vector, axis=1)
print("\nColumn vector:")
print(column_vector)

print("column_vector shape:", column_vector.shape)


# 4. Транспонування column_vector
column_vector_T = column_vector.T
print("\nТранспонований column_vector:")
print(column_vector_T)

print("\nРозміри:")
print("column_vector shape:", column_vector.shape)
print("column_vector_T shape:", column_vector_T.shape)

Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]]

Вектор і його транспонування:
vector: [0.65303345 0.95452228 0.873951   0.06056304 0.71269916 0.64643997
 0.50160009 0.87348049 0.35970846 0.24782755]
vector_T: [0.65303345 0.95452228 0.873951   0.06056304 0.71269916 0.64643997
 0.50160009 0.87348049 0.35970846 0.24782755]

Розміри:
vector shape: (10,)
vector_T shape: (10,)

Column vector:
[[0.65303345]
 [0.95452228]
 [0.873951  ]
 [0.06056304]
 [0.71269916]
 [0.64643997]
 [0.50160009]
 [0.87348049]
 [0.35970846]
 [0.24782755]]
column_vector shape: (10, 1)

Транспонований column_vector:
[[0.65303345 0.95452228 0.873951   0.06056304 0.71269916 0.64643997
  0.50160009 0.87348049 0.35970846 0.24782755]]

Розміри:
column_vector shape: (10, 1)
column_vector_T shape: (1, 10)
